#!/bin/sh

function find_merge() {
	git log --date=short --pretty='%P %H %cd'  $1 ^$2 --ancestry-path | tail -1
}

function format_short_sha1() {
	cat $1 | cut -c 1-7;
}

function branch_sha1() {
	git rev-parse $1 | format_short_sha1;
}
	
function first_commit() {
	git log --oneline master..$1 | tail -1 | format_short_sha1;
}

function list_not_deleted_merged_remotes() { 
	#trap 'break 2' INT
	git branch -r --sort=authordate | grep ${1:-''} | 
	while read -r branch; do 
		test $? -gt 0 && break 2;
		branch=$(cut -f1 -d ' ' <<< $branch); 
		test $? -gt 0 && break 2;
		notMergedCommitsCount=$(git rev-list --count master..$branch); 
		test $? -gt 0 && break 2;
		if [ $notMergedCommitsCount -eq 0 ]; 
		then 
			echo $branch; 
		fi; 
	done; 
}

function print_merged_remotes(){
	echo -ne '\033[1;36mFirst   Last    Merge   Date       Autor\033[14CRemote branch\033[0m \n'; 
	trap 'exit' INT
	list_not_deleted_merged_remotes $1 | 
	while read -r remote; do 
		test $? -gt 0 && break;
		mergeCommitInfo=$(find_merge master $remote); 
		test $? -gt 0 && break;
		masterMergeParent=$(cut -f1 -d ' ' <<< $mergeCommitInfo); 
		test $? -gt 0 && break;
		lastCommit=$(cut -f2 -d ' ' <<< $mergeCommitInfo); 
		test $? -gt 0 && break;
		if [ ${#mergeCommitInfo} -eq 133 ]
		then
			mergeCommit=$(cut -f3 -d ' ' <<< $mergeCommitInfo | format_short_sha1); 
			test $? -gt 0 && break;
			mergeCommitDate=$(cut -f4 -d ' ' <<< $mergeCommitInfo); 
			firstCommitInfo=$(git log --format=format:'%h %an' $masterMergeParent..$lastCommit | tail -1); 
			test $? -gt 0 && break;
			masterMergeParent=$(format_short_sha1 <<< $masterMergeParent);
		else
			continue
		fi
		test $? -gt 0 && break;
		lastCommit=$(format_short_sha1 <<< $lastCommit);
		test $? -gt 0 && break;
		firstCommit=$(cut -f1 -d ' ' <<< $firstCommitInfo | format_short_sha1); 
		test $? -gt 0 && break;
		firstCommitAuthor=$(cut -c 9- <<< $firstCommitInfo); 
		test $? -gt 0 && break;
		echo -ne $firstCommit $lastCommit $mergeCommit $mergeCommitDate'\033[1;31m' $firstCommitAuthor '\033[0m\r\033[53C' $remote '\n';  
		test $? -gt 0 && break;
	done; 
}

print_merged_remotes $1
