#!/bin/sh
git rev-list $2..$1 --count --pretty=oneline | tr -d "\n";
printf " not merged commits from: %s to: %s\n\n" "$1" "$2";
git --no-pager log $2..$1 --reverse --pretty=oneline --format=format:"%C(bold blue)%h%C(reset)%C(dim green) %an%C(reset) %C(white)%s%C(reset) %C(dim white) %C(bold green)(%ar) %C(reset)";